apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vhia
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vhia
    app.kubernetes.io/part-of: bflorkie-11-april
  name: devfile-sample-vhia
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vhia
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vhia
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:2a319230771300a6552361f91665e1405ae38b494b0c6a126b41a20796391c57
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
