apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vhia
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vhia
    app.kubernetes.io/part-of: bflorkie-11-april
  name: devfile-sample-vhia
  namespace: bflorkie-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-vhia
status:
  loadBalancer: {}
